CREATE VIEW DAILY_SALES_VW AS 
SELECT ORDERDATE,
SPLIT_PART(PURCHASEADDRESS, ',', 2) AS CITY,
PRODUCT, CATEGORY,
SUM(QUANTITYORDERED) AS QUANTITYORDERED,
SUM(QUANTITYORDERED * PRICEEACH) AS SALES
FROM SALES_DATA
GROUP BY ORDERDATE, CITY, PRODUCT, CATEGORY
ORDER BY ORDERDATE