CREATE OR REPLACE VIEW GOLD_DIM_PRODUCT_VW AS 
-- Esta vista crea la dimensión de producto con un ID único para cada producto y categoría.
SELECT RANK() OVER (ORDER BY PRODUCT, CATEGORY) AS PRODUCTID,
PRODUCT, CATEGORY
FROM DAILY_SALES_VW
GROUP BY PRODUCT, CATEGORY;

CREATE OR REPLACE VIEW GOLD_DIM_CITY_VW AS 
-- Esta vista crea la dimensión de ciudad con un ID único para cada ciudad.
SELECT RANK() OVER (ORDER BY CITY) AS CITYID,
CITY
FROM DAILY_SALES_VW
GROUP BY CITY;


CREATE OR REPLACE VIEW GOLD_DIM_CALENDAR_VW AS 
-- Esta vista crea la dimensión de ciudad con un ID único para cada ciudad.
SELECT 
ORDERDATE,
EXTRACT(DAY FROM ORDERDATE) AS DDAY,
EXTRACT(MONTH FROM ORDERDATE) AS DMONTH,
EXTRACT(YEAR FROM ORDERDATE) AS DYEAR,
EXTRACT(DAYOFWEEK FROM ORDERDATE) AS DDAYOFWEEK,
EXTRACT(WEEK FROM ORDERDATE) AS DWEEK,
FROM (SELECT DISTINCT ORDERDATE FROM DAILY_SALES_VW) AS DD;

CREATE OR REPLACE VIEW GOLD_FACT_SALES_VW AS 
-- Esta vista crea la dimensión de ciudad con un ID único para cada ciudad.
SELECT 
S.ORDERDATE,
DP.PRODUCTID,
DC.CITYID,
S.QUANTITYORDERED,
S.SALES
FROM DAILY_SALES_VW AS S
JOIN GOLD_DIM_PRODUCT_VW AS DP ON S.PRODUCT = DP.PRODUCT AND S.CATEGORY = DP.CATEGORY
JOIN GOLD_DIM_CITY_VW AS DC ON S.CITY = DC.CITY