SELECT C1.NOMBRE, C2.NOMBRE, C1.CIUDAD
FROM CLIENTES C1, CLIENTES C2
WHERE C1.CIUDAD = C2.CIUDAD AND C1.NOMBRE <> C2.NOMBRE


-- TABLA CLIENTES TIENE 1000 REGISTROS
-- EL CLIENTE 1 SE COMPARA CON LOS 999 RESTANTES
