CREATE OR REPLACE TABLE DATABUSTER_SAMPLE.PUBLIC.SALES_DATA2 (
    Product STRING,
    QuantityOrdered NUMBER,
    PriceEach NUMBER,
    OrderDate DATE,
    PurchaseAddress STRING,
    Category STRING
) CLUSTER BY (Product);



COPY INTO DATABUSTER_SAMPLE.PUBLIC.SALES_DATA2
FROM @internal_sales_stage
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"')
ON_ERROR = 'CONTINUE';


ALTER SESSION SET USE_CACHED_RESULT = FALSE;

SELECT 
EXTRACT(YEAR FROM ORDERDATE) AS DYEAR, 
CASE 
    WHEN MONTH(ORDERDATE) IN (1,2,3) THEN 'Q1'
    WHEN MONTH(ORDERDATE) IN (4,5,6) THEN 'Q2'
    WHEN MONTH(ORDERDATE) IN (7,8,9) THEN 'Q3'
    WHEN MONTH(ORDERDATE) IN (10,11,12) THEN 'Q4'
END AS QS,
SUM(QUANTITYORDERED * PRICEEACH) AS SALES
FROM SALES_DATA
WHERE PRODUCT = 'iPhone'
GROUP BY DYEAR, QS
ORDER BY DYEAR, QS;

SELECT 
EXTRACT(YEAR FROM ORDERDATE) AS DYEAR, 
CASE 
    WHEN MONTH(ORDERDATE) IN (1,2,3) THEN 'Q1'
    WHEN MONTH(ORDERDATE) IN (4,5,6) THEN 'Q2'
    WHEN MONTH(ORDERDATE) IN (7,8,9) THEN 'Q3'
    WHEN MONTH(ORDERDATE) IN (10,11,12) THEN 'Q4'
END AS QS,
SUM(QUANTITYORDERED * PRICEEACH) AS SALES
FROM SALES_DATA2
WHERE PRODUCT = 'iPhone'
GROUP BY DYEAR, QS
ORDER BY DYEAR, QS;