SELECT 
EXTRACT(YEAR FROM ORDERDATE) AS DYEAR, 
CASE 
    WHEN MONTH(ORDERDATE) IN (1,2,3) THEN 'Q1'
    WHEN MONTH(ORDERDATE) IN (4,5,6) THEN 'Q2'
    WHEN MONTH(ORDERDATE) IN (7,8,9) THEN 'Q3'
    WHEN MONTH(ORDERDATE) IN (10,11,12) THEN 'Q4'
END AS QS,
SUM(QUANTITYORDERED * PRICEEACH) AS SALES
FROM SALES_DATA
WHERE SPLIT_PART(PURCHASEADDRESS, ',', 2) = ' Boston'
GROUP BY DYEAR, QS
ORDER BY DYEAR, QS;

SELECT 
EXTRACT(YEAR FROM ORDERDATE) AS DYEAR, 
CASE 
    WHEN MONTH(ORDERDATE) IN (1,2,3) THEN 'Q1'
    WHEN MONTH(ORDERDATE) IN (4,5,6) THEN 'Q2'
    WHEN MONTH(ORDERDATE) IN (7,8,9) THEN 'Q3'
    WHEN MONTH(ORDERDATE) IN (10,11,12) THEN 'Q4'
END AS QS,
SUM(QUANTITYORDERED * PRICEEACH) AS SALES
FROM SALES_DATA
WHERE PURCHASEADDRESS LIKE '%Boston%'
GROUP BY DYEAR, QS
ORDER BY DYEAR, QS








